services:
  sensor-objeto-1:
    build: 
      context: ./sensor1
      dockerfile: dockerfile
    network_mode: "host" # Usa o IP real da máquina para alcançar o Broker
    restart: on-failure

  sensor-objeto-2:
    build: 
      context: ./sensor2
      dockerfile: dockerfile
    network_mode: "host" # Garante que o tráfego UDP saia pela placa de rede física
    restart: on-failure