# imagem base
FROM golang:1.25-alpine

#diretório de trabalho
WORKDIR /app

#copiar arquivos
COPY . .

#compilar o binário
RUN go build -o server .

#expor portas TCP e UDP
EXPOSE 4041/tcp
EXPOSE 4042/udp
EXPOSE 8983/tcp

#rodar aplicação
CMD ["./server"]